# Generated by Django 2.1.7 on 2019-02-24 01:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repos.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('avatar_id', models.URLField(blank=True)),
                ('gravatar_id', models.URLField(blank=True)),
                ('type', models.CharField(max_length=24)),
                ('login', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('blog', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=192)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('synchronized_at', models.DateTimeField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('following', models.ManyToManyField(related_name='followers', through='users.Follower', to='users.GithubUser')),
                ('forking', models.ManyToManyField(related_name='forks', through='users.Fork', to='repos.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repos.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.GithubUser')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repos.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.GithubUser')),
            ],
        ),
        migrations.AddField(
            model_name='githubuser',
            name='stars',
            field=models.ManyToManyField(related_name='stargazers', through='users.Star', to='repos.Repository'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='watching',
            field=models.ManyToManyField(related_name='subscribers', through='users.Watch', to='repos.Repository'),
        ),
        migrations.AddField(
            model_name='fork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.GithubUser'),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.GithubUser'),
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.GithubUser'),
        ),
    ]
