# Generated by Django 2.1.7 on 2019-03-22 18:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=120)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('payload', jsonfield.fields.JSONField(default=dict)),
                ('api', models.CharField(max_length=32)),
                ('public', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
